export const dummyData=[
    {
        id:1,
        title1:"The OG Creators",
        title2:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        ViewAll:"ViewAll",
        image: "image1tanmay.jpeg",
        name1:"Tanmay Bhatt",
        name2:"Tanmay Bhatt",
        followers1:"1.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:2,
        image: "KushaKapila_1.jpg",
        name1:"Kusha Kapila",
        name2:"Kusha Kapila",
        followers1:"3.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:3,
        image: "rohan.webp",
        name1:"Rohan Joshi",
        name2:"Rohan Joshi",
        followers1:"597K",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    },
    {
        id:4,
        image: "image4.webp",
        name1:"Bhuvan Bam",
        name2:"Bhuvan Bam",
        followers1:"19.9M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    
    },


    {
        id:5,
        title1:"In The Spotlight",
        title2:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        ViewAll:"ViewAll",
        image: "images.jpeg",
        name1:"Sharan Hegde",
        name2:"Sharan Hegde",
        followers1:"2.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:6,
        image: "dolly.png",
        name1:"Dolly Singh",
        name2:"Dolly Singh",
        followers1:"3.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:7,
        image: "images (1).jpeg",
        name1:"kritika Khurana",
        name2:"kritika Khurana",
        followers1:"1.8M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    },
    {
        id:8,
        image: "image4.webp",
        name1:"Bhuvan Bam",
        name2:"Bhuvan Bam",
        followers1:"19.9M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    
    },
    {
        id:9,
        title1:"On The Rise",
        title2:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        ViewAll:"ViewAll",
        image: "image1tanmay.jpeg",
        name1:"Tanmay Bhatt",
        name2:"Tanmay Bhatt",
        followers1:"1.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:10,
        image: "KushaKapila_1.jpg",
        name1:"Kusha Kapila",
        name2:"Kusha Kapila",
        followers1:"3.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:11,
        image: "rohan.webp",
        name1:"Rohan Joshi",
        name2:"Rohan Joshi",
        followers1:"597K",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    },
    {
        id:12,
        image: "image4.webp",
        name1:"Bhuvan Bam",
        name2:"Bhuvan Bam",
        followers1:"19.9M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    
    },

    {
        id:13,
        title1:"UGC",
        title2:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        ViewAll:"ViewAll",
        image: "images.jpeg",
        name1:"Sharan Hegde",
        name2:"Sharan Hegde",
        followers1:"2.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:14,
        image: "dolly.png",
        name1:"Dolly Singh",
        name2:"Dolly Singh",
        followers1:"3.7M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",

    },
    {
        id:15,
        image: "images (1).jpeg",
        name1:"kritika Khurana",
        name2:"kritika Khurana",
        followers1:"1.8M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    },
    {
        id:16,
        image: "image4.webp",
        name1:"Bhuvan Bam",
        name2:"Bhuvan Bam",
        followers1:"19.9M",
        followers2:"Followers",
        image1:"instagram icon .png",
        image2:"youtube_icon.png",
        image3:"facebook.png",
    }



]